# -*- mode: yaml -*-

jobs:
- job: osx
  pool:
    vmImage: macOS-10.13
  timeoutInMinutes: 360
  steps:
  - script: |
      cmake .  -DSIDX_BUILD_TESTS=ON 
    displayName: 'CMake'
  - script: |
      make
    displayName: 'Build'
  - script: |
      make test
    displayName: 'Test'
  - script: |
      make dist
    displayName: 'Dist'